movies = [
    {
        "id": 1,
        "title": "Interstellar",
        "director": "Christopher Nolan",
        "directorId": 1,
        "releaseDate": "2014-11-07",
        "rating": 9.3,
        "isWatched": True,
        "genre": "Sci-Fi",
        "runtime": 169,
        "country": "USA / UK",
        "language": "English",
        "tagline": "Love is the one thing that transcends time and space.",
        "summary": "A team of explorers travels through a wormhole in space to ensure humanity has a future.",
        "posterUrl": "/assets/images/1.jpg",
        "status": "showing",
    },
    {
        "id": 2,
        "title": "Inception",
        "director": "Christopher Nolan",
        "directorId": 1,
        "releaseDate": "2010-07-16",
        "rating": 9.2,
        "isWatched": True,
        "genre": "Sci-Fi",
        "runtime": 148,
        "country": "USA / UK",
        "language": "English",
        "tagline": "Your mind is the scene of the crime.",
        "summary": "A skilled thief enters people's dreams to steal secrets and attempts one final high-risk mission.",
        "posterUrl": "/assets/images/2.jpg",
        "status": "archived",
    },
    {
        "id": 3,
        "title": "The Dark Knight",
        "director": "Christopher Nolan",
        "directorId": 1,
        "releaseDate": "2008-07-18",
        "rating": 9.1,
        "isWatched": False,
        "genre": "Action",
        "runtime": 152,
        "country": "USA / UK",
        "language": "English",
        "tagline": "Welcome to a world without rules.",
        "summary": "Batman, Gordon, and Dent push back against organized crime while facing the chaos created by the Joker.",
        "posterUrl": "/assets/images/3.jpg",
        "status": "showing",
    },
    {
        "id": 4,
        "title": "Crouching Tiger, Hidden Dragon",
        "director": "Ang Lee",
        "directorId": 2,
        "releaseDate": "2000-07-07",
        "rating": 8.9,
        "isWatched": True,
        "genre": "Wuxia",
        "runtime": 120,
        "country": "China / Taiwan / Hong Kong",
        "language": "Mandarin",
        "tagline": "A timeless tale of love and honor.",
        "summary": "A legendary sword and tangled relationships draw warriors into a story of duty, desire, and sacrifice.",
        "posterUrl": "/assets/images/4.jpg",
        "status": "archived",
    },
    {
        "id": 5,
        "title": "Life of Pi",
        "director": "Ang Lee",
        "directorId": 2,
        "releaseDate": "2012-11-21",
        "rating": 8.8,
        "isWatched": False,
        "genre": "Drama",
        "runtime": 127,
        "country": "USA / Taiwan",
        "language": "English",
        "tagline": "Believe the unbelievable.",
        "summary": "After a shipwreck, a young man survives on a lifeboat with a Bengal tiger, confronting faith and survival.",
        "posterUrl": "/assets/images/5.jpg",
        "status": "showing",
    },
    {
        "id": 6,
        "title": "Spirited Away",
        "director": "Hayao Miyazaki",
        "directorId": 3,
        "releaseDate": "2001-07-20",
        "rating": 9.4,
        "isWatched": True,
        "genre": "Animation",
        "runtime": 125,
        "country": "Japan",
        "language": "Japanese",
        "tagline": "A coming-of-age in a spirit world.",
        "summary": "A girl trapped in a mysterious spirit realm works to save her parents and find her way back.",
        "posterUrl": "/assets/images/6.jpg",
        "status": "showing",
    },
    {
        "id": 7,
        "title": "My Neighbor Totoro",
        "director": "Hayao Miyazaki",
        "directorId": 3,
        "releaseDate": "1988-04-16",
        "rating": 8.9,
        "isWatched": True,
        "genre": "Animation",
        "runtime": 86,
        "country": "Japan",
        "language": "Japanese",
        "tagline": "A gentle childhood fantasy.",
        "summary": "Two sisters in rural Japan encounter magical woodland spirits while adjusting to a new life.",
        "posterUrl": "/assets/images/1.jpg",
        "status": "archived",
    },
    {
        "id": 8,
        "title": "In the Mood for Love",
        "director": "Wong Kar-wai",
        "directorId": 4,
        "releaseDate": "2000-09-29",
        "rating": 8.7,
        "isWatched": False,
        "genre": "Drama",
        "runtime": 98,
        "country": "Hong Kong, China",
        "language": "Cantonese",
        "tagline": "A restrained romance in neon shadows.",
        "summary": "Two neighbors discover their spouses' affair and gradually form a complex emotional bond.",
        "posterUrl": "/assets/images/2.jpg",
        "status": "archived",
    },
    {
        "id": 9,
        "title": "Chungking Express",
        "director": "Wong Kar-wai",
        "directorId": 4,
        "releaseDate": "1994-07-14",
        "rating": 8.6,
        "isWatched": False,
        "genre": "Romance",
        "runtime": 102,
        "country": "Hong Kong, China",
        "language": "Cantonese",
        "tagline": "Two stories of loneliness and connection.",
        "summary": "Two drifting policemen and two women cross paths in a city where timing changes everything.",
        "posterUrl": "/assets/images/3.jpg",
        "status": "archived",
    },
]

directors = [
    {
        "id": 1,
        "name": "Christopher Nolan",
        "nationality": "UK / USA",
        "birthYear": 1970,
        "bio": "Known for nonlinear storytelling and large-scale visual design. Major works include Inception, Interstellar, and The Dark Knight trilogy.",
    },
    {
        "id": 2,
        "name": "Ang Lee",
        "nationality": "Taiwan / USA",
        "birthYear": 1954,
        "bio": "A cross-cultural filmmaker known for balancing character drama and visual innovation, including Crouching Tiger, Hidden Dragon and Life of Pi.",
    },
    {
        "id": 3,
        "name": "Hayao Miyazaki",
        "nationality": "Japan",
        "birthYear": 1941,
        "bio": "Co-founder of Studio Ghibli and one of animation cinema's most influential directors, with works such as Spirited Away and My Neighbor Totoro.",
    },
    {
        "id": 4,
        "name": "Wong Kar-wai",
        "nationality": "Hong Kong, China",
        "birthYear": 1958,
        "bio": "Renowned for poetic visual language and emotionally layered stories. Representative films include In the Mood for Love and Chungking Express.",
    },
]


def next_movie_id():
    return max((movie["id"] for movie in movies), default=0) + 1


def next_director_id():
    return max((director["id"] for director in directors), default=0) + 1
